/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guis.employee;

import cm2100guicw.Bread;
import cm2100guicw.Menu;
import cm2100guicw.Sandwich;
import guis.EmployeeFrame;
import java.awt.Dimension;
import java.awt.KeyboardFocusManager;
import java.awt.event.ActionEvent;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.KeyStroke;

/**
 *
 * @author Michal
 */
public class AddSandwichFrame extends javax.swing.JDialog {

    /**
     * Creates new form AddSandwichFrame
     */
    public AddSandwichFrame(java.awt.Frame parent, boolean modal, EmployeeFrame employee) {
        super(parent, modal);
        this.employee = employee;
        initComponents();
        addSandwichButton.requestFocus();
        
        focusListener = new FocusListener(){
        
            @Override
            public void focusGained(FocusEvent fe){
            
                ((JTextField) fe.getSource()).setText("");
                ((JTextField) fe.getSource()).setEditable(true);
            
            }
            
            @Override 
            public void focusLost(FocusEvent fe){}
        
        };
        
        nameTextField.addFocusListener(focusListener);
        fillingTextField.addFocusListener(focusListener);
        
        addKeyListeners();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        priceLabel = new javax.swing.JLabel();
        priceTextField = new javax.swing.JTextField();
        fillingLabel = new javax.swing.JLabel();
        fillingTextField = new javax.swing.JTextField();
        breadLabel = new javax.swing.JLabel();
        breadComboBox = new javax.swing.JComboBox<>();
        addPriceButton = new javax.swing.JButton();
        addSandwichButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        addImageLabel = new javax.swing.JLabel();
        browseButton = new javax.swing.JButton();
        addImageCheckBox = new javax.swing.JCheckBox();
        imageFileNameLabel = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);

        nameLabel.setText("Name:");

        nameTextField.setText("Enter name here...");
        nameTextField.setName("nameTextField"); // NOI18N
        nameTextField.setNextFocusableComponent(addPriceButton);

        priceLabel.setText("Price:");

        priceTextField.setEnabled(false);
        priceTextField.setNextFocusableComponent(fillingTextField);

        fillingLabel.setText("Filling:");

        fillingTextField.setText("Filling like item1+item2+item3");
        fillingTextField.setName("fillingTextField"); // NOI18N
        fillingTextField.setNextFocusableComponent(breadComboBox);

        breadLabel.setText("Bread:");

        breadComboBox.setModel(new DefaultComboBoxModel(Bread.values()));
        breadComboBox.setNextFocusableComponent(addImageCheckBox);

        addPriceButton.setText("Add Price");
        addPriceButton.setNextFocusableComponent(priceTextField);
        addPriceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPriceButtonActionPerformed(evt);
            }
        });

        addSandwichButton.setText("Add Sandwich");
        addSandwichButton.setNextFocusableComponent(cancelButton);
        addSandwichButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSandwichButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.setNextFocusableComponent(nameTextField);
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        addImageLabel.setText("Add Photo?");

        browseButton.setText("Browse");
        browseButton.setEnabled(false);
        browseButton.setNextFocusableComponent(addSandwichButton);
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        addImageCheckBox.setText("Yes");
        addImageCheckBox.setName(""); // NOI18N
        addImageCheckBox.setNextFocusableComponent(browseButton);
        addImageCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addImageCheckBoxActionPerformed(evt);
            }
        });

        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageFileNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addImageLabel)
                        .addGap(18, 18, 18)
                        .addComponent(addImageCheckBox)
                        .addGap(18, 18, 18)
                        .addComponent(browseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addSandwichButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameLabel)
                                    .addComponent(priceLabel)
                                    .addComponent(fillingLabel)
                                    .addComponent(breadLabel))
                                .addGap(79, 79, 79)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nameTextField)
                                    .addComponent(fillingTextField)
                                    .addComponent(breadComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(addPriceButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                        .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLabel)
                    .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addPriceButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fillingLabel)
                    .addComponent(fillingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(breadLabel)
                    .addComponent(breadComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addImageLabel)
                    .addComponent(addImageCheckBox)
                    .addComponent(browseButton))
                .addGap(18, 18, 18)
                .addComponent(imageFileNameLabel)
                .addGap(18, 18, 18)
                .addComponent(imageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addSandwichButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addPriceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPriceButtonActionPerformed
        
        NumberDialog dialog = new NumberDialog(((JFrame) this.getParent()), true, this);
        dialog.setVisible(true);
        
    }//GEN-LAST:event_addPriceButtonActionPerformed

    private void addSandwichButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSandwichButtonActionPerformed
        
        try{
        
            String name = nameTextField.getText();
            int price = Integer.parseInt(priceTextField.getText());
            String filling = fillingTextField.getText();
            
            if(name.isEmpty() || name.equals("Enter name here..."))
                JOptionPane.showMessageDialog(this, "Name cannot be empty. Please enter the name.");
            
            else if(filling.equals("Filling like item1+item2+item3"))
                JOptionPane.showMessageDialog(this, "Filling cannot be empty. Please enter the filling.");
            
            else{
            
                Bread bread = (Bread) breadComboBox.getSelectedItem();
                Sandwich sandwich = new Sandwich(name, price, filling, bread);
                
                if(addImageCheckBox.isSelected()){
                
                    String fileName = imageFileNameLabel.getText();
                    fileName = fileName.substring(fileName.indexOf(":") + 2);
                    sandwich.setImageFileName(fileName);
                
                }
                    
                employee.addSandwich(sandwich);

                System.out.println("New Sandwich added.");

                this.dispose();
            
            }
            
        }
        catch(NumberFormatException ex){
        
            System.out.println(ex.toString());
            JOptionPane.showMessageDialog(this, "Price cannot be empty. Please enter the price.");
        
        }
        
    }//GEN-LAST:event_addSandwichButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void addImageCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addImageCheckBoxActionPerformed
        browseButton.setEnabled(((JCheckBox) evt.getSource()).isSelected());
    }//GEN-LAST:event_addImageCheckBoxActionPerformed

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed

        try{
        
            JFileChooser jfc = new JFileChooser(System.getProperty("user.dir") + "/images/");
            jfc.showSaveDialog(this);
            String imageFileName = jfc.getSelectedFile().getName();
            imageFileNameLabel.setText("Image file name: " + imageFileName);
            imageLabel.setIcon(new ImageIcon("images/sandwiches/" + imageFileName));
            this.setMinimumSize(new Dimension(this.getWidth(), this.getHeight() + 100));
        
        }
        catch(NullPointerException ex){
            System.out.println(ex.toString());
        }
        
    }//GEN-LAST:event_browseButtonActionPerformed

    public void setPrice(int a){
        priceTextField.setText("" + a);
    }
    
    private void addKeyListeners(){
    
        this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(
            KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "EXIT");
        
        this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(
            KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "ENTER");
        
        this.getRootPane().getActionMap().put("EXIT", new AbstractAction(){
            
            @Override
            public void actionPerformed(ActionEvent ae){
            
                AddSandwichFrame.this.dispose();
                
            }
        });
        
        this.getRootPane().getActionMap().put("ENTER", new AbstractAction(){
        
            @Override
            public void actionPerformed(ActionEvent ae){
            
                JComponent source = (JComponent) KeyboardFocusManager.getCurrentKeyboardFocusManager().getFocusOwner();
                
                if(source instanceof JButton)
                    ((JButton) source).doClick();
                
                else if(source instanceof JTextField){
                
                    if(source.getName().equals("nameTextField"))
                        addPriceButton.requestFocus();
                    else if(source.getName().equals("fillingTextField           "))
                        breadComboBox.requestFocus();
                    
                }
                
                else if(source instanceof JCheckBox){
                
                    ((JCheckBox) source).setSelected(!((JCheckBox) source).isSelected());
                    browseButton.setEnabled(!browseButton.isEnabled());
                
                }
                
            }
        
        });
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSandwichFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSandwichFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSandwichFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSandwichFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddSandwichFrame dialog = new AddSandwichFrame(new javax.swing.JFrame(), true, new EmployeeFrame(new JFrame(), true, new Menu("Menu")));
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    
    private EmployeeFrame employee;
    private FocusListener focusListener;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox addImageCheckBox;
    private javax.swing.JLabel addImageLabel;
    private javax.swing.JButton addPriceButton;
    private javax.swing.JButton addSandwichButton;
    private javax.swing.JComboBox<String> breadComboBox;
    private javax.swing.JLabel breadLabel;
    private javax.swing.JButton browseButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel fillingLabel;
    private javax.swing.JTextField fillingTextField;
    private javax.swing.JLabel imageFileNameLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextField priceTextField;
    // End of variables declaration//GEN-END:variables
}
