/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guis.employee;

import java.awt.KeyboardFocusManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.KeyStroke;

/**
 *
 * @author Michal
 */
public class NumberDialog extends javax.swing.JDialog {

    /**
     * Creates new form NumberDialog
     * @param parent Parent frame, Customer or Employee
     * @param modal is this modal 
     * @param dialog Parent dialog
     */
    public NumberDialog(java.awt.Frame parent, boolean modal, JDialog dialog) {
        super(parent, modal);
        this.dialog = dialog;
        price = 0;
        initComponents();
        
        listener = new ActionListener(){
        
            @Override
            public void actionPerformed(ActionEvent ae){
            
                if(priceLabel.getText().equals("Price goes here")){
                
                    priceLabel.setText("");
                    
                }
                    
                String sourceText = ((JButton) ae.getSource()).getText();
                if(!sourceText.equals("OK") && !sourceText.equals("Cancel"))
                    priceLabel.setText(priceLabel.getText() + sourceText);

                price = Integer.parseInt(priceLabel.getText());
                    
            }
        
        };
        
        jButton1.addActionListener(listener);
        jButton2.addActionListener(listener);
        jButton3.addActionListener(listener);
        jButton4.addActionListener(listener);
        jButton5.addActionListener(listener);
        jButton6.addActionListener(listener);
        jButton7.addActionListener(listener);
        jButton8.addActionListener(listener);
        jButton9.addActionListener(listener);
        jButton10.addActionListener(listener);
        
        jButton1.requestFocus();
        
        addKeyListeners();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        priceLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(1, 1));

        priceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceLabel.setText("Price goes here");
        jPanel1.add(priceLabel);

        jPanel2.setLayout(new java.awt.GridLayout(4, 3));

        jButton1.setText("1");
        jButton1.setNextFocusableComponent(jButton2);
        jPanel2.add(jButton1);

        jButton2.setText("2");
        jButton2.setNextFocusableComponent(jButton3);
        jPanel2.add(jButton2);

        jButton3.setText("3");
        jButton3.setNextFocusableComponent(jButton4);
        jPanel2.add(jButton3);

        jButton4.setText("4");
        jButton4.setNextFocusableComponent(jButton5);
        jPanel2.add(jButton4);

        jButton5.setText("5");
        jButton5.setNextFocusableComponent(jButton6);
        jPanel2.add(jButton5);

        jButton6.setText("6");
        jButton6.setNextFocusableComponent(jButton7);
        jPanel2.add(jButton6);

        jButton7.setText("7");
        jButton7.setNextFocusableComponent(jButton8);
        jPanel2.add(jButton7);

        jButton8.setText("8");
        jButton8.setNextFocusableComponent(jButton9);
        jPanel2.add(jButton8);

        jButton9.setText("9");
        jButton9.setNextFocusableComponent(jButton10);
        jPanel2.add(jButton9);

        jButton11.setText("OK");
        jButton11.setNextFocusableComponent(jButton12);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton11);

        jButton10.setText("0");
        jButton10.setNextFocusableComponent(jButton11);
        jPanel2.add(jButton10);

        jButton12.setText("Cancel");
        jButton12.setNextFocusableComponent(jButton1);
        jPanel2.add(jButton12);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        
        if(dialog instanceof AddDrinkFrame)
            ((AddDrinkFrame) dialog).setPrice(price);
        else if(dialog instanceof AddSandwichFrame)
            ((AddSandwichFrame) dialog).setPrice(price);
        else if(dialog instanceof AddSideFrame)
            ((AddSideFrame) dialog).setPrice(price);
        
        this.dispose();
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void addKeyListeners(){
    
        this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(
            KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "EXIT");
        
        this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(
            KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "ENTER");
        
        this.getRootPane().getActionMap().put("EXIT", new AbstractAction(){
            
            @Override
            public void actionPerformed(ActionEvent ae){
            
                NumberDialog.this.dispose();
                
            }
        });
        
        this.getRootPane().getActionMap().put("ENTER", new AbstractAction(){
        
            @Override
            public void actionPerformed(ActionEvent ae){
            
                JButton source = (JButton) KeyboardFocusManager.getCurrentKeyboardFocusManager().getFocusOwner();
                
                source.doClick();
                
            }
        
        });
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NumberDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NumberDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NumberDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NumberDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NumberDialog dialog = new NumberDialog(new javax.swing.JFrame(), true, new JDialog(new JFrame(), "Dialog", true));
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private ActionListener listener;
    private JDialog dialog;
    private int price;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel priceLabel;
    // End of variables declaration//GEN-END:variables
}
