/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guis;

import guis.employee.AddSideFrame;
import guis.employee.AddSandwichFrame;
import guis.employee.AddDrinkFrame;
import cm2100guicw.Drink;
import cm2100guicw.Menu;
import cm2100guicw.MenuItem;
import cm2100guicw.Sandwich;
import cm2100guicw.Side;
import java.awt.KeyboardFocusManager;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author Michal
 */
public class EmployeeFrame extends javax.swing.JDialog {

    /**
     * Creates new form EmployeeFrame
     */
    public EmployeeFrame(java.awt.Frame parent, boolean modal, Menu menu) {
        
        super(parent, modal);
        this.menu = menu;
        initComponents();
        addKeyListeners();
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jScrollPane1 = new javax.swing.JScrollPane();
        drinkList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        sideList = new javax.swing.JList<>();
        addDrinkButton = new javax.swing.JButton();
        addSandwichButton = new javax.swing.JButton();
        addSideButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        sandwichList = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        loadMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        logoutMenu = new javax.swing.JMenu();
        logoutMenuItem = new javax.swing.JMenuItem();
        exitMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("Employee Form"), this, org.jdesktop.beansbinding.BeanProperty.create("title"));
        bindingGroup.addBinding(binding);

        drinkList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        drinkList.setFocusable(false);
        drinkList.setNextFocusableComponent(addDrinkButton);
        jScrollPane1.setViewportView(drinkList);

        sideList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        sideList.setFocusable(false);
        sideList.setNextFocusableComponent(addSideButton);
        jScrollPane3.setViewportView(sideList);

        addDrinkButton.setText("Add Drink");
        addDrinkButton.setNextFocusableComponent(addSandwichButton);
        addDrinkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDrinkButtonActionPerformed(evt);
            }
        });

        addSandwichButton.setText("Add Sandwich");
        addSandwichButton.setNextFocusableComponent(addSideButton);
        addSandwichButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSandwichButtonActionPerformed(evt);
            }
        });

        addSideButton.setText("Add Side");
        addSideButton.setNextFocusableComponent(addDrinkButton);
        addSideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSideButtonActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(sandwichList);

        fileMenu.setText("File");

        loadMenuItem.setText("Load Data");
        loadMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(loadMenuItem);

        saveMenuItem.setText("Save Data");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveMenuItem);

        jMenuBar1.add(fileMenu);

        logoutMenu.setText("Logout");

        logoutMenuItem.setText("Logout to main screen");
        logoutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuItemActionPerformed(evt);
            }
        });
        logoutMenu.add(logoutMenuItem);

        jMenuBar1.add(logoutMenu);

        exitMenu.setText("Exit");

        exitMenuItem.setText("Close the Application");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        exitMenu.add(exitMenuItem);

        jMenuBar1.add(exitMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addDrinkButton, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(addSandwichButton, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(addSideButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addDrinkButton)
                    .addComponent(addSandwichButton)
                    .addComponent(addSideButton))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addDrinkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDrinkButtonActionPerformed
        
        AddDrinkFrame frame = new AddDrinkFrame((JFrame) this.getParent(), true, this);
        this.setVisible(false);
        frame.setVisible(true);
        
        this.setVisible(true);
        
    }//GEN-LAST:event_addDrinkButtonActionPerformed

    private void addSandwichButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSandwichButtonActionPerformed
        
        AddSandwichFrame frame = new AddSandwichFrame((JFrame) this.getParent(), true, this);
        this.setVisible(false);
        frame.setVisible(true);
        
        this.setVisible(true);
        
    }//GEN-LAST:event_addSandwichButtonActionPerformed

    private void addSideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSideButtonActionPerformed
        
        AddSideFrame frame = new AddSideFrame((JFrame) this.getParent(), true, this);
        this.setVisible(false);
        frame.setVisible(true);
        
        this.setVisible(true);
        
    }//GEN-LAST:event_addSideButtonActionPerformed

    private void loadMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadMenuItemActionPerformed
        
        JFileChooser jfc = new JFileChooser(System.getProperty("user.dir"));
        jfc.showOpenDialog(this);
        menu.readFromFile(jfc.getSelectedFile());
        
        loadDrinks();
        loadSandwiches();
        loadSides();
        
    }//GEN-LAST:event_loadMenuItemActionPerformed

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        
        JFileChooser jfc = new JFileChooser(System.getProperty("user.dir"));
        jfc.showSaveDialog(this);
        menu.saveToFile(jfc.getSelectedFile());
        JOptionPane.showMessageDialog(this, "Data has been saved.");
        
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void logoutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuItemActionPerformed
        this.dispose();
    }//GEN-LAST:event_logoutMenuItemActionPerformed

    private void loadDrinks(){
    
        DefaultListModel model = new DefaultListModel();
        drinkList.setModel(model);
        
        for(MenuItem d: menu.getItems()){
        
            if(d instanceof Drink)
                model.addElement((Drink) d);
        
        }
        
    }
    
    private void loadSandwiches(){
    
        DefaultListModel model = new DefaultListModel();
        sandwichList.setModel(model);
        
        for(MenuItem s: menu.getItems())
        
            if(s instanceof Sandwich)
                model.addElement((Sandwich) s);
            
    }
    
    private void loadSides(){
    
        DefaultListModel model = new DefaultListModel();
        sideList.setModel(model);
        
        for(MenuItem s: menu.getItems())
            if(s instanceof Side)
                model.addElement((Side) s);
    
    }
    
    public void addDrink(Drink d){
    
        this.menu.addMenuItem(d);
        loadDrinks();
    
    }
    
    public void addSandwich(Sandwich s){
    
        this.menu.addMenuItem(s);
        loadSandwiches();
    
    }
    
    public void addSide(Side s){
    
        this.menu.addMenuItem(s);
        loadSides();
    
    }
    
    private void addKeyListeners(){
    
        this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(
            KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "EXIT");
        
        this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(
            KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "ENTER");
        
        this.getRootPane().getActionMap().put("EXIT", new AbstractAction(){
            
            @Override
            public void actionPerformed(ActionEvent ae){
            
                logoutMenu.doClick();
                
            }
        });
        
        this.getRootPane().getActionMap().put("ENTER", new AbstractAction(){
        
            @Override
            public void actionPerformed(ActionEvent ae){
            
                JButton source = (JButton) KeyboardFocusManager.getCurrentKeyboardFocusManager().getFocusOwner();
                
                ((JButton) source).doClick();
                
            }
        
        });
    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EmployeeFrame dialog = new EmployeeFrame(new javax.swing.JFrame(), true, new Menu("Menu"));
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private Menu menu;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDrinkButton;
    private javax.swing.JButton addSandwichButton;
    private javax.swing.JButton addSideButton;
    private javax.swing.JList<String> drinkList;
    private javax.swing.JMenu exitMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JMenuItem loadMenuItem;
    private javax.swing.JMenu logoutMenu;
    private javax.swing.JMenuItem logoutMenuItem;
    private javax.swing.JList<String> sandwichList;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JList<String> sideList;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
